name: Introduction to CI/CD - Testing & Linting

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  testing:
    name: Unit Test
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository onto the runner
        uses: actions/checkout@v3

      - name: setup python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.10'

      - name: install dependencies
        run: make pip-init && make build

      - name: pytest
        run: make test
  
  linting:
    name: Flake8 Lint
    needs: testing
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository onto the runner
        uses: actions/checkout@v3

      - name: setup python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.10'

      - name: flake8 lint
        uses: py-actions/flake8@v2
